<a href="https://colab.research.google.com/github/Twinklingstar374/SectionB_G3_RetailAnalytics/blob/main/Cleaned_new_retail_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("new_retail_data.csv")

In [ ]:
shape = df.shape
shape

(302010, 30)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isna().sum()

Transaction_ID      333
Customer_ID         308
Name                382
Email               347
Phone               362
Address             315
City                248
State               281
Zipcode             340
Country             271
Age                 173
Gender              317
Income              290
Customer_Segment    215
Date                359
Year                350
Month               273
Time                350
Total_Purchases     361
Amount              356
Total_Amount        350
Product_Category    283
Product_Brand       281
Product_Type          0
Feedback            184
Shipping_Method     337
Payment_Method      297
Order_Status        235
Ratings             184
products              0
dtype: int64

In [ ]:
drop_cols = [
    'Name', 'Email', 'Phone', 'Address', 'Zipcode'
]
df.drop(columns=drop_cols, inplace=True)

KeyError: "['Name', 'Email', 'Phone', 'Address', 'Zipcode'] not found in axis"

In [ ]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Total_Purchases'].fillna(0, inplace=True)
df['Amount'].fillna(df['Amount'].median(), inplace=True)
df['Total_Amount'].fillna(df['Total_Amount'].median(), inplace=True)

/tmp/ipykernel_7659/1420267287.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipykernel_7659/1420267287.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total_Purchases'].fillna(0, inplace=True)
/tmp/ipykernel_7659/1420267287.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Amount'].fillna(df['Amount'].median(), inplace=True)
/tmp/ipykernel_7659/1420267287.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total_Amount'].fillna(df['Total_Amount'].median(), inplace=True)

In [ ]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Customer_Segment'].fillna('Unknown', inplace=True)
df['Feedback'].fillna('No Feedback', inplace=True)
df['Order_Status'].fillna('Pending', inplace=True)
df['Payment_Method'].fillna('Unknown', inplace=True)
df['Shipping_Method'].fillna('Standard', inplace=True)
df['Income'].fillna(df['Income'].mode()[0], inplace=True)

/tmp/ipykernel_7659/1097996820.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
/tmp/ipykernel_7659/1097996820.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Segment'].fillna('Unknown', inplace=True)
/tmp/ipykernel_7659/1097996820.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Feedback'].fillna('No Feedback', inplace=True)
/tmp/ipykernel_7659/1097996820.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Status'].fillna('Pending', inplace=True)
/tmp/ipykernel_7659/1097996820.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Method'].fillna('Unknown', inplace=True)
/tmp/ipykernel_7659/1097996820.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Shipping_Method'].fillna('Standard', inplace=True)
/tmp/ipykernel_7659/1097996820.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income'].fillna(df['Income'].mode()[0], inplace=True)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Date'].fillna(method='ffill', inplace=True)

df['Time'].fillna('00:00:00', inplace=True)

/tmp/ipykernel_7659/147825122.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_7659/147825122.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Date'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_7659/147825122.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Time'].fillna('00:00:00', inplace=True)

In [ ]:
df['avg_order_value'] = df['Total_Amount'] / df['Total_Purchases']
df['avg_order_value'].fillna(0, inplace=True)

/tmp/ipykernel_7659/1653657929.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['avg_order_value'].fillna(0, inplace=True)

In [ ]:
def age_group(age):
    if age < 25:
        return 'Young'
    elif age < 45:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['Age'].apply(age_group)

In [ ]:
def purchase_type(x):
    if x <= 5:
        return 'Low'
    elif x <= 15:
        return 'Medium'
    else:
        return 'High'

df['purchase_category'] = df['Total_Purchases'].apply(purchase_type)

In [ ]:
def revenue_category(x):
    if x < 1000:
        return 'Low'
    elif x < 5000:
        return 'Medium'
    else:
        return 'High'

df['revenue_category'] = df['Total_Amount'].apply(revenue_category)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

df['day'] = df['Date'].dt.day
df['weekday'] = df['Date'].dt.day_name()
df['is_weekend'] = df['weekday'].isin(['Saturday', 'Sunday'])

In [ ]:
df['order_success'] = df['Order_Status'].apply(lambda x: 1 if x == 'Completed' else 0)

In [ ]:
def rating_label(x):
    if x >= 4:
        return 'Good'
    elif x >= 2:
        return 'Average'
    else:
        return 'Poor'

df['rating_category'] = df['Ratings'].apply(rating_label)

In [ ]:
def customer_value(row):
    if row['Total_Amount'] > 5000 and row['Total_Purchases'] > 10:
        return 'High Value'
    elif row['Total_Amount'] > 2000:
        return 'Medium Value'
    else:
        return 'Low Value'

df['customer_value_segment'] = df.apply(customer_value, axis=1)

In [ ]:
df

,Transaction_ID,Customer_ID,City,State,Country,Age,Gender,Income,Customer_Segment,Date,...,avg_order_value,age_group,purchase_category,revenue_category,day,weekday,is_weekend,order_success,rating_category,customer_value_segment
0,8691788.0,37249.0,Dortmund,Berlin,Germany,21.0,Male,Low,Regular,2023-09-18,...,108.028757,Young,Low,Low,18,Monday,False,0,Good,Low Value
1,2174773.0,69749.0,Nottingham,England,UK,19.0,Female,Low,Premium,2023-12-31,...,403.353907,Young,Low,Low,31,Sunday,True,0,Good,Low Value
2,6679610.0,30192.0,Geelong,New South Wales,Australia,48.0,Male,Low,Regular,2023-04-26,...,354.477600,Senior,Low,Medium,26,Wednesday,False,0,Average,Low Value
3,7232460.0,62101.0,Edmonton,Ontario,Canada,56.0,Male,High,Premium,2023-05-08,...,352.407717,Senior,Medium,Medium,8,Monday,False,0,Good,Medium Value
4,4983775.0,27901.0,Bristol,England,UK,22.0,Male,Low,Premium,2024-01-10,...,124.276525,Young,Low,Low,10,Wednesday,False,0,Poor,Low Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302005,4246475.0,12104.0,Townsville,New South Wales,Australia,31.0,Male,Medium,Regular,2024-01-20,...,194.792597,Adult,Low,Low,20,Saturday,True,0,Poor,Low Value
302006,1197603.0,69772.0,Hanover,Berlin,Germany,35.0,Female,Low,New,2023-12-28,...,285.137301,Adult,Low,Low,28,Thursday,False,0,Good,Low Value
302007,7743242.0,28449.0,Brighton,England,UK,41.0,Male,Low,Premium,2024-02-27,...,60.701762,Adult,Low,Low,27,Tuesday,False,0,Average,Low Value
302008,9301950.0,45477.0,Halifax,Ontario,Canada,41.0,Male,Medium,New,2023-09-03,...,120.834784,Adult,Low,Low,3,Sunday,True,0,Good,Low Value
302009,2882826.0,53626.0,Tucson,West Virginia,USA,28.0,Female,Low,Premium,2024-01-08,...,340.319060,Adult,Medium,Medium,8,Monday,False,0,Average,Medium Value